### PR TITLE
fix: do not add extra newlines for csv encoder

### PR DESCRIPTION
**Pull request by xwjdsh**
fix https://github.com/xo/usql/issues/297

### CODE REVIEW

**Comment by kenshaw** [comment]
I don't believe this is correct logic. There should be an extra empty line after each result set. Can you copy/paste output that you think is incorrect with an actual data set, please?

**Comment by xwjdsh** [comment]
image
As described in the linked issue, The last line of the result will have an extra newline (from the `EncodeAll` method). For the last result set, the CSV encoder should not add a new line, this change delayed the addition of line breaks, skip if no next result set.

**Comment by kenshaw** [comment]
I don't believe this PR is the right way to fix this issue. This extra newline (which I'm not sure is really "extra"), is most likely from `usql`'s behavior. I'll look at this, and possibly enable some better logic so that when its in a non-interactive shell, the additonal newline is not added.

In the addition, if the intention is to use `usql` to script a query, I'd suggest passing it through some other Unix command line tool (`sed`, `perl`, `awk`, ...) to trim this.

**Comment by xwjdsh** [comment]
You are right, I'm too one-sided. I noticed that the JSON encoder has the same logic but no problem, close this PR, and I will try to find the right way...

**Comment by kenshaw** [comment]
@xwjdsh you were correct; there was a superfluous newline. You just chose the wrong one. I have a change incoming.

**Pull request closed without merging**
